### PR TITLE
feat: add stackStrategy docs

### PR DESCRIPTION
**Pull request by villebro**
Docs for the `stackStrategy` feature proposed in https://github.com/apache/echarts/pull/17086

### CODE REVIEW

**Comment by villebro** [comment]
Ping @pissang @Ovilia @susiwen8 is this PR ok to be merged now that the feature PR has been merged?

**Comment by susiwen8** [comment]
Could you add `version`? Since this will be introduced in `5.3.3`

**Comment by villebro** [comment]
> Could you add `version`? Since this will be introduced in `5.3.3` @pissang Are we prepare to land this feature in `5.3.3`?

Thanks @susiwen8 - I added the version here: https://github.com/apache/echarts-doc/pull/255/commits/d4d6baa63619caa69b7c70ae19029f3be78cd035

**Comment by susiwen8** [comment]
Since `5.3.3` isn't published, so it better to merge this PR after release

**Comment by pissang** [comment]
Added Chinese translation and merged to dev branch

**Pull request merged**
