### PR TITLE
Fix(emphasis.focus): sankey have adjacency focus

### PR DESCRIPTION
**Pull request by susiwen8**
Fix https://github.com/apache/echarts/issues/14549

### CODE REVIEW

**Comment by susiwen8** [comment]
Or maybe `sankey` is `isGraph`?

**Comment by pissang** [comment]
Thanks! `sankey` use `isGraph` seems better

**Comment by susiwen8** [comment]
@pissang Can we merge this?

**Comment by lijia150** [comment]
but how about (sankey.emphasis.focus) with (series/ancestor/descendant)

**Comment by susiwen8** [comment]
@lijia150  Sorry it not supported yet

**Pull request merged**
